name = 'conditional_context'
version = '1.1.0'
description = 'Context manager that will skip the body on a condition.'
url = 'https://github.com/justengel/conditional_context'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
